### ISSUE TITLE
Would you consider re-licensing this repository?

### ISSUE THREAD

**Issue by arfon** [Cykey/Sublime-Logos#5]
Hello there, we'd love to use this library to syntax-highlight files on GitHub but in order to do so we need this library to have a more permissive license.

If you don't have any particular reason for choosing GPL would you be willing to consider switching this to a more permissive license such as MIT, BSD or Apache 2?

Many thanks
Arfon (GitHub Staff)

**Comment by Cykey** [comment]
Not sure where you're expecting to use this library on GitHub, considering that this is for Sublime Text. Could you please clarify?

Cheers,
David

**Comment by arfon** [comment]
Hi David

Thanks for your reply. We use Sublime, Textmate and Atom grammars to syntax-highlight files on GitHub. This is pretty much the only Logos library I can find. 

You can read more here if you're curious: https://github.com/github/linguist

Thanks for considering this request :-)

**Comment by Cykey** [comment]
Alright, done. :) See commit e783d38b9ce09c147b00fee971d125a69b9ad96a

David

**Comment by arfon** [comment]
👍 many thanks!
